package dev.shipkaro.kit.core.security

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.flow.map
import timber.log.Timber
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import android.util.Base64

private val Context.secureDataStore: androidx.datastore.core.DataStore<Preferences>
    by preferencesDataStore(name = "kit_secure_prefs")

/**
 * Encrypted key-value store for app-level secrets the developer wants to persist
 * themselves — e.g. a user-entered API key, an OAuth refresh token from a backend the
 * SDKs don't already handle.
 *
 * Crypto:
 *  - AES-256/GCM/NoPadding.
 *  - Key material lives in Android Keystore (`AndroidKeyStore` provider) — never
 *    extracted into app memory; protected by the device's hardware-backed keystore
 *    when available (HW-KM / StrongBox), falls back to software keystore otherwise.
 *  - One master key per install, alias `kit_secure_master_key`. Survives across launches,
 *    deleted with the app or via [clear].
 *  - Fresh 12-byte IV per write, packed `iv ‖ ciphertext+tag`, Base64-encoded, stored
 *    in a dedicated DataStore Preferences file (`kit_secure_prefs`) — kept separate from
 *    the regular `kit_settings` file so a backup-strip or device migration handles them
 *    independently if needed.
 *
 * Out of scope:
 *  - Auth tokens already managed by Supabase / Firebase / RevenueCat SDKs — those SDKs
 *    do their own keystore work. Don't duplicate them here.
 *  - Keys provided via `local.properties` → BuildConfig (those are build-time, not
 *    user-entered).
 *
 * Single Koin singleton — see [coreModule] in `AppModules.kt`.
 */
class SecureDataStore(context: Context) {

    private val appContext = context.applicationContext
    private val masterKey: SecretKey by lazy { loadOrCreateMasterKey() }

    suspend fun putString(key: String, value: String) {
        val (iv, ciphertext) = encrypt(value.toByteArray(Charsets.UTF_8))
        val packed = pack(iv, ciphertext)
        appContext.secureDataStore.edit { it[stringPreferencesKey(key)] = packed }
    }

    suspend fun getString(key: String): String? = observe(key).firstOrNull()

    fun observe(key: String): Flow<String?> = appContext.secureDataStore.data.map { prefs ->
        prefs[stringPreferencesKey(key)]?.let { runCatching { decryptPacked(it) }.getOrNull() }
    }

    suspend fun remove(key: String) {
        appContext.secureDataStore.edit { it.remove(stringPreferencesKey(key)) }
    }

    suspend fun clear() {
        appContext.secureDataStore.edit { it.clear() }
    }

    private fun encrypt(plaintext: ByteArray): Pair<ByteArray, ByteArray> {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, masterKey)
        val iv = cipher.iv // 12 bytes for GCM, generated by the cipher
        val ciphertext = cipher.doFinal(plaintext)
        return iv to ciphertext
    }

    private fun decryptPacked(packed: String): String {
        val bytes = Base64.decode(packed, Base64.NO_WRAP)
        require(bytes.size > IV_LENGTH) { "Ciphertext too short" }
        val iv = bytes.copyOfRange(0, IV_LENGTH)
        val ciphertext = bytes.copyOfRange(IV_LENGTH, bytes.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, masterKey, GCMParameterSpec(GCM_TAG_BITS, iv))
        return cipher.doFinal(ciphertext).toString(Charsets.UTF_8)
    }

    private fun pack(iv: ByteArray, ciphertext: ByteArray): String =
        Base64.encodeToString(iv + ciphertext, Base64.NO_WRAP)

    private fun loadOrCreateMasterKey(): SecretKey {
        val keystore = KeyStore.getInstance(KEYSTORE).apply { load(null) }
        keystore.getKey(KEY_ALIAS, null)?.let { return it as SecretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                .setRandomizedEncryptionRequired(true) // forces fresh IV per encryption
                .build(),
        )
        return generator.generateKey().also {
            Timber.tag(TAG).i("Generated new SecureDataStore master key")
        }
    }

    companion object {
        private const val TAG = "SecureDataStore"
        private const val KEYSTORE = "AndroidKeyStore"
        private const val KEY_ALIAS = "kit_secure_master_key"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val IV_LENGTH = 12
        private const val GCM_TAG_BITS = 128
        private const val KEY_SIZE_BITS = 256
    }
}

